# Generated by Django 5.2.4 on 2025-07-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_contact_submitted_at_contact_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='username',
            field=models.CharField(default='anonymus', max_length=100),
            preserve_default=False,
        ),
    ]
