# Generated by Django 5.2.4 on 2025-07-31 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_message_game_deatil_alter_game_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='deatil',
            new_name='message',
        ),
    ]
