# Generated by Django 5.2.4 on 2025-08-01 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_rename_deatil_game_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='games/'),
            preserve_default=False,
        ),
    ]
